services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dca-bot
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - ./logs:/app/logs
      - ./:/app
    networks:
      - dca-network
    stop_grace_period: 1s

networks:
  dca-network:
    driver: bridge
